#!/usr/bin/env python
from optparse import OptionParser
import logging

from levislib.agent import Agent

if __name__ == "__main__":

    # Setup logging
    logging.basicConfig(filename='agent.log',
                        level=logging.DEBUG,
                        format='%(asctime)s,%(msecs)d %(levelname)s %(threadName)s %(message)s',
                        datefmt='%H:%M:%S')

    # VARIABLES AND STUFF
    agent_conf = {
        "agent_id":   "cfe5964d-59f8-4479-ba40-9e6134ed88da",
        "log_file":   "agent.log",
        "task_file":  "agent.tasks",
        "host":       "127.0.0.1",
        "port":       11300
    }
    
    a = Agent(agent_conf)
    a.start()
    while a.running:
        try:
            i=raw_input()
            if i in ['q','e','c']:
                a.stop()
                break
            elif i in ['i']:
                logging.debug("WORKERS %s." % repr(a.workers))
        except KeyboardInterrupt:
            logging.debug("User wants to exit...")
            a.stop()
            break
